### ISSUE TITLE
Please provide version for Frege 3.24

### ISSUE THREAD

**Issue by dbushenko** [januslynd/chinook#7]
Can't use current chinook with Frege 3.24... :-(

**Comment by mariogarcia** [comment]
Apparently in Frege 3.24 Lambda is replaced by Lazy: 

https://github.com/Frege/frege/wiki/Calling-Frege-from-Java-(from-release-3.24-on)

I'm on it :+1:

**Comment by dbushenko** [comment]
Cool, thanks! Can't wait for it!

**Comment by mariogarcia** [comment]
`status`: Chinook is compiling ok with Frege `3.24` but there're still some issues with `:chinook:sample` module.

**Comment by mariogarcia** [comment]
`status`: 
- Chinook code is working
- `Diablo` dependencies should change. `Diablo` is compiled against jdk 1.8 and `Chinook` is compiled against 1.7

Once I release a new `Diablo` version (I hope it will happen today) I will be able to generate a new version of `Chinook` against probably frege `3.24-7.100`

**Comment by mariogarcia** [comment]
Released `Chinook` version `0.2.1`. Please note that it was compiled against `frege` 3.24-7.100 meaning it is compiled with jdk target `1.7`
