### ISSUE TITLE
build fails on 1.8

### ISSUE THREAD

**Issue by ghost** [januslynd/chinook#9]
Hi there,

When I try to build chinook-sample, it fails during the final stage.  I am using openjdk-8 (do I have to use Oracle instead?). I tried to use instead 1.7, but then spark-core complained that it needed major.minor 52. Unfortunately, I am not sufficiently familiar with the java ecosystem to figure this out on my own (I am coming from Haskell), so I would appreciate any suggestion. I include below the error and part of the stacktrace produced.

Thank you,

George

---

$ gradle -a run --stacktrace
:chinook-sample:compileJava UP-TO-DATE
:chinook-sample:compileFrege UP-TO-DATE
:chinook-sample:processResources UP-TO-DATE
:chinook-sample:classes UP-TO-DATE
:chinook-sample:run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
:chinook-sample:run FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':chinook-sample:run'.
  
  > Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 100
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':chinook-sample:run'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)

**Comment by mariogarcia** [comment]
Nope no need for Oracle. This is the output for `java -version`

```
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

It seems you're not using the `gradle wrapper` could you try again with the wrapper ?

`./gradlew -a run`

I've realized the gradle wrapper version is `2.6`. For next release I should be updating that too, it's a little bit old.

**Comment by ghost** [comment]
This is my `java -version`:

```
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

And here is the output of `./gradlew  -a run`

```
./gradlew -a run
:chinook-sample:compileJava UP-TO-DATE
:chinook-sample:compileFrege
:chinook-sample:processResources UP-TO-DATE
:chinook-sample:classes
:chinook-sample:run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
:chinook-sample:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chinook-sample:run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 100

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.254 secs
```

**Comment by mariogarcia** [comment]
It's really weird. They only way I could reproduce it is when I tried to run the sample app when the port was already taken by another instance.  

I don't have time now, but next thing I'm gonna do is to activate all logging traces to see what's really happening, and I'll try to get back to you asap.

Thanks for the feedback George

**Comment by ghost** [comment]
Wow. Sorry to bother you with such a trivial issue. 8080 was already taken: once I changed the port everything worked out.

Thanks a lot.

**Comment by mariogarcia** [comment]
No worrries and thanks for the feedback, it's clear that in future releases there should be more logging information.
